version: "3.8"

services:
  redis:
    image: redis:latest
    networks:
      - pypi-network

  proxy:
    image: ghcr.io/khj809/keycloak-basic-auth-proxy:latest
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_BASE_URL: "https://keycloak.mydomain.com"
      KEYCLOAK_REALM: "<keycloak-realm>"
      KEYCLOAK_CLIENT_ID: "<keycloak-client>"
      KEYCLOAK_CLIENT_SECRET: "<keycloak-client-secret>"
      PROXY_UPSTREAM_URL: "http://pypiserver:8080"
      PROXY_AUTH_COOKIE_NAME: "pypiserver:auth_token"
      PROXY_TOKEN_CACHE_ENABLED: "True"
      PROXY_TOKEN_CACHE_URL: "redis:6379/0"
    depends_on:
      - redis
    networks:
      - pypi-network
    stop_grace_period: 0s

  pypiserver:
    image: pypiserver/pypiserver:latest
    command: ["-P", ".", "-a", ".", "/data"]
    volumes:
      - pypi-data:/data
    networks:
      - pypi-network
    stop_grace_period: 0s

networks:
  pypi-network:
    driver: bridge

volumes:
  pypi-data:
